More bug fixes. Still needs to be reinstalled from scratch.

diff --git a/ember-satellite-projects/crystallise/crystallise b/ember-satellite-projects/crystallise/crystallise
--- a/ember-satellite-projects/crystallise/crystallise
+++ b/ember-satellite-projects/crystallise/crystallise
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Crystallise
 # Version:
-export crystalliseVersion='2.13.3.2'
+export crystalliseVersion='2.13.3.3'
 
 # You need a file named config.txt in your home directory with a title, a collection identifier, a passphrase, and your desired directory to contain temporary files, each in its own line.
 
@@ -54,5 +54,10 @@ ia upload "$CrystalID" --retries=10 --metadata="subject:Uploaded using Crystalli
 #Clear the screen
 printf "\033c"
 
-echo "Done! The new crystal's address is:"
-echo "$CrystalID"
+if [ -s "./$CrystalID.coal5-timestamp" ]; then
+    echo "Done! The new crystal's address is:"
+    echo "$CrystalID"
+else
+    echo "Crystallisation failed! This is bad!"
+    exit 1
+fi
diff --git a/ember-satellite-projects/crystallise/decrystallise b/ember-satellite-projects/crystallise/decrystallise
--- a/ember-satellite-projects/crystallise/decrystallise
+++ b/ember-satellite-projects/crystallise/decrystallise
@@ -51,5 +51,10 @@ mv -v "./$CrystalLogID."!(coal5-meta) "./$CrystalLogID.coal5-meta/"
 #Clear the screen
 printf "\033c"
 
-echo "Done! The crystal has been extracted to:"
-echo "$(pwd)/$CrystalLogID"
+if [ -s "./$CrystalLogID.coal5-tend" ]; then
+    echo "Done! The crystal has been extracted to:"
+    echo "$(pwd)/$CrystalLogID"
+else
+    echo "Crystallisation failed! This is bad!"
+    exit 1
+fi
